#!/usr/bin/env bash
# manifest-lib.sh — generate the superskills-marketing plugin: a flat shim tree
# plus its manifest.
#
# Two Claude Code plugin-loader facts drive this (verified by evals/ on
# 2.1.273): skills are discovered only as direct children of a listed
# directory (<dir>/<skill>/SKILL.md, no recursion), and a plugin skill's slash
# name is the DIRECTORY basename, not the frontmatter `name:`. marketing-skills
# nests skills 1–3 deep and 100 of its 174 directory names differ from the
# frontmatter name users know (`seo/local` → `/local-seo`, and two skills share
# the basename `article`). So the plugin points at one generated directory,
# plugin-skills/, holding a relative symlink <frontmatter-name> → ../<path>
# for every skill. ./setup is unaffected: its `find -type f` does not follow
# symlinked directories. Dependency-free (no jq). Tested in tests/manifest-lib.bats.

MARKETING_SHIM_DIR="plugin-skills"

# The frontmatter-name rule lives in one place, shared with ./setup and the doctor.
# shellcheck source=scripts/lib/skills-lib.sh
. "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/skills-lib.sh"

# skill_entries <root>
# Print "<frontmatter name>\t<relative dir>" for every skill under <root>,
# sorted by name. Falls back to the directory basename when `name:` is absent.
skill_entries() {
  local root="$1" f rel name
  marketing_skill_files "$root" |
  while IFS= read -r f; do
    rel="${f#"${root%/}"/}"; rel="${rel%/SKILL.md}"
    [ "$rel" = "SKILL.md" ] && continue   # a SKILL.md at the root itself is not a nested skill
    name="$(skill_name_from "$f" "$(basename "$rel")")"
    printf '%s\t%s\n' "$name" "$rel"
  done | sort
}

# write_marketing_shims <root> [entries]
# Rebuild <root>/plugin-skills/ so it holds exactly one relative symlink per
# skill, named by frontmatter name. Returns 1 on a duplicate name (two skills
# would collide as one slash command) so the caller can fail loudly.
# [entries] is skill_entries output already computed by the caller (walking
# 174 SKILL.md files takes ~1 s); omitted, it is computed here.
write_marketing_shims() {
  local root="$1" entries="${2-}" name rel prev="" shim
  shim="$root/$MARKETING_SHIM_DIR"   # separate line: `local a=$1 b=$a` expands b before a is set
  [ -n "$root" ] && [ -d "$root" ] || { echo "write_marketing_shims: bad root '$root'" >&2; return 1; }
  [ $# -ge 2 ] || entries="$(skill_entries "$root")"
  rm -rf "$shim"; mkdir -p "$shim"
  while IFS=$'\t' read -r name rel; do
    [ -z "$name" ] && continue
    if [ "$name" = "$prev" ]; then
      echo "ERROR: two marketing skills share the name '$name' (second at $rel)" >&2
      return 1
    fi
    prev="$name"
    # The name becomes a path component under plugin-skills/: refuse anything
    # that could escape it or be misparsed (../x, absolute, spaces, slashes).
    case "$name" in
      *[!A-Za-z0-9._-]*|-*|.*|"") echo "ERROR: unsafe skill name '$name' at $rel (letters, digits, . _ - only; must not start with - or .)" >&2; return 1 ;;
    esac
    ln -s "../$rel" "$shim/$name"
  done <<< "$entries"
}

# write_marketing_manifest <root> <version> <out_file> [skill_count]
write_marketing_manifest() {
  local root="$1" version="$2" out="$3" count="${4-}"
  [ -n "$count" ] || count="$(skill_entries "$root" | wc -l | tr -d ' ')"
  mkdir -p "$(dirname "$out")"
  {
    printf '{\n'
    printf '  "name": "superskills-marketing",\n'
    printf '  "displayName": "Superskills Marketing",\n'
    printf '  "version": "%s",\n' "$version"
    printf '  "description": "The %s marketing skills from superskills (SEO, content, pages, ads, channels, strategies) as a Claude Code plugin. Generated by scripts/sync-marketing-manifest.sh — do not hand-edit.",\n' "$count"
    printf '  "author": { "name": "Danilo Stern-Sapad", "email": "danilosapad@gmail.com", "url": "https://github.com/ariadoss" },\n'
    printf '  "homepage": "https://github.com/ariadoss/superskills",\n'
    printf '  "repository": "https://github.com/ariadoss/superskills",\n'
    printf '  "license": "MIT",\n'
    printf '  "keywords": ["marketing", "seo", "content", "ads", "growth", "skills"],\n'
    printf '  "skills": ["./%s"]\n' "$MARKETING_SHIM_DIR"
    printf '}\n'
  } > "$out"
}
