#!/usr/bin/env bash
# manifest-lib.sh — generate the superskills-marketing plugin: a flat shim tree
# plus its manifest.
#
# Two Claude Code plugin-loader facts drive this (verified by evals/ on
# 2.1.273): skills are discovered only as direct children of a listed
# directory (<dir>/<skill>/SKILL.md, no recursion), and a plugin skill's slash
# name is the DIRECTORY basename, not the frontmatter `name:`. marketing-skills
# nests skills 1–3 deep and 100 of its 174 directory names differ from the
# frontmatter name users know (`seo/local` → `/local-seo`, and two skills share
# the basename `article`). So the plugin points at one generated directory,
# plugin-skills/, holding a relative symlink <frontmatter-name> → ../<path>
# for every skill. ./setup is unaffected: its `find -type f` does not follow
# symlinked directories. Dependency-free (no jq). Tested in tests/manifest-lib.bats.

MARKETING_SHIM_DIR="plugin-skills"

# The frontmatter-name rule lives in one place, shared with ./setup and the doctor.
# shellcheck source=scripts/lib/skills-lib.sh
. "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/skills-lib.sh"

# skill_entries <root>
# Print "<frontmatter name>\t<relative dir>" for every skill under <root>,
# sorted by name. Falls back to the directory basename when `name:` is absent.
skill_entries() {
  local root="${1%/}"
  # One batch name lookup (skill_names_from_files) instead of three processes
  # per skill; rel is the path below <root> without /SKILL.md.
  marketing_skill_files "$root" | skill_names_from_files | awk -F'\t' -v root="$root/" '
    index($1, root) == 1 {
      rel = substr($1, length(root) + 1); sub(/\/SKILL\.md$/, "", rel)
      if (rel != "SKILL.md" && rel != "") print $2 "\t" rel
    }' | LC_ALL=C sort
}

# write_marketing_shims <root> [entries]
# Rebuild <root>/plugin-skills/ so it holds exactly one relative symlink per
# skill, named by frontmatter name. Returns 1 on a duplicate name (two skills
# would collide as one slash command) so the caller can fail loudly.
# [entries] is skill_entries output already computed by the caller (walking
# 174 SKILL.md files takes ~1 s); omitted, it is computed here.
write_marketing_shims() {
  local root="$1" entries="${2-}" name rel shim
  shim="$root/$MARKETING_SHIM_DIR"   # separate line: `local a=$1 b=$a` expands b before a is set
  [ -n "$root" ] && [ -d "$root" ] || { echo "write_marketing_shims: bad root '$root'" >&2; return 1; }
  [ $# -ge 2 ] || entries="$(skill_entries "$root")"
  # Validate everything before touching the existing tree: a bad name or a
  # duplicate must not leave the plugin with an empty or half-built shim dir.
  # Duplicates are found over the whole list, not by adjacency after a sort.
  local dup
  dup="$(printf '%s\n' "$entries" | cut -f1 | grep -v '^$' | LC_ALL=C sort | uniq -d | head -1)"
  if [ -n "$dup" ]; then
    echo "ERROR: two marketing skills share the name '$dup'" >&2
    return 1
  fi
  while IFS=$'\t' read -r name rel; do
    [ -z "$name" ] && continue
    # The name becomes a path component under plugin-skills/: refuse anything
    # that could escape it or be misparsed (../x, absolute, spaces, slashes).
    case "$name" in
      *[!A-Za-z0-9._-]*|-*|.*) echo "ERROR: unsafe skill name '$name' at $rel (letters, digits, . _ - only; must not start with - or .)" >&2; return 1 ;;
    esac
  done <<< "$entries"
  local staging="$root/.$MARKETING_SHIM_DIR.new"
  rm -rf "$staging"; mkdir -p "$staging"
  while IFS=$'\t' read -r name rel; do
    [ -z "$name" ] && continue
    ln -s "../$rel" "$staging/$name"
  done <<< "$entries"
  # Swap by rename (old aside, new in), not delete-then-rebuild-in-place: a
  # concurrent reader can see plugin-skills/ briefly absent (an unavoidable gap
  # between two renames), but never half-built with some entries stale and some
  # new — and a crash between the two renames leaves the previous tree intact
  # at .plugin-skills.old for the next run (or a maintainer) to recover.
  local old="$root/.$MARKETING_SHIM_DIR.old"
  rm -rf "$old"
  [ -e "$shim" ] && mv "$shim" "$old"
  mv "$staging" "$shim"
  rm -rf "$old"
}

# write_marketing_manifest <root> <version> <out_file> [skill_count]
write_marketing_manifest() {
  local root="$1" version="$2" out="$3" count="${4-}"
  [ -n "$count" ] || count="$(skill_entries "$root" | wc -l | tr -d ' ')"
  mkdir -p "$(dirname "$out")"
  {
    printf '{\n'
    printf '  "name": "superskills-marketing",\n'
    printf '  "displayName": "Superskills Marketing",\n'
    printf '  "version": "%s",\n' "$version"
    printf '  "description": "The %s marketing skills from superskills (SEO, content, pages, ads, channels, strategies) as a Claude Code plugin. Generated by scripts/sync-marketing-manifest.sh — do not hand-edit.",\n' "$count"
    printf '  "author": { "name": "Danilo Stern-Sapad", "email": "danilosapad@gmail.com", "url": "https://github.com/ariadoss" },\n'
    printf '  "homepage": "https://github.com/ariadoss/superskills",\n'
    printf '  "repository": "https://github.com/ariadoss/superskills",\n'
    printf '  "license": "MIT",\n'
    printf '  "keywords": ["marketing", "seo", "content", "ads", "growth", "skills"],\n'
    printf '  "skills": ["./%s"]\n' "$MARKETING_SHIM_DIR"
    printf '}\n'
  } > "$out"
}
